# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: avbot
open_collective: # Replace with a single Open Collective username
ko_fi: avbot
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: avbot
liberapay: avbot
issuehunt: avbot
otechie: # Replace with a single Otechie username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
